services:
  backend:
    image: ${ECR_REGISTRY}/nestjs-ecommerce-backend:${IMAGE_TAG:-dev}
    container_name: backend_api
    restart: always
    expose:
      - "3001"
    environment:
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@${RDS_ENDPOINT}:5432/${DB_NAME:-lab_ghislain}?sslmode=verify-full
      NODE_EXTRA_CA_CERTS: /certs/rds-global-bundle.pem
    volumes:
      - ./rds-global-bundle.pem:/certs/rds-global-bundle.pem:ro

  frontend:
    image: ${ECR_REGISTRY}/nestjs-ecommerce-frontend:${IMAGE_TAG:-dev}
    container_name: frontend_app
    restart: always
    expose:
      - "3000"
    depends_on:
      - backend

  proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "8085:80"
    volumes:
      - ./nginx.aws.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
