# Version de l'API pour les déploiements
apiVersion: apps/v1
# Type de ressource : Deployment
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: lab-devops
  labels:
    app: frontend
spec:
  # 2 répliques pour la Haute Disponibilité
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: node:20-alpine
          ports:
            - containerPort: 3000 # Port de l'application Web React
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
