# Version de l'API Kubernetes
apiVersion: v1
# Type de ressource : Secret (Stockage sécurisé d'informations sensibles)
kind: Secret
metadata:
  # Nom du secret
  name: postgres-secret
  # Namespace dans lequel le secret sera créé
  namespace: lab-devops
# Type par défaut pour les paires clé-valeur opaques
type: Opaque
# Données sous forme de texte clair (K8s s'occupe de les sécuriser en mémoire)
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secretpassword
  POSTGRES_DB: lab_ghislain
